{
  lib,
  flk,
  ...
}:
{
  home-manager.users.${flk.user} =
    { config, ... }:
    {
      fonts.fontconfig.configFile =
        let
          mkFontconfigConf = conf: ''
            <?xml version='1.0'?>

            <!-- Generated by Home Manager. -->

            <!DOCTYPE fontconfig SYSTEM 'urn:fontconfig:fonts.dtd'>
            <fontconfig>
            ${conf}
            </fontconfig>
          '';
        in
        {
          fonts = lib.mkForce {
            enable = true;
            priority = 10;
            source = null;
            text = mkFontconfigConf ''
              <description>Add fonts in the Nix user profile</description>

              <include ignore_missing="yes">${config.home.path}/etc/fonts/conf.d</include>
              <include ignore_missing="yes">${config.home.path}/etc/fonts/fonts.conf</include>

              <dir>${config.home.path}/lib/X11/fonts</dir>
              <dir>${config.home.path}/share/fonts</dir>
              <dir>${config.home.profileDirectory}/lib/X11/fonts</dir>
              <dir>${config.home.profileDirectory}/share/fonts</dir>

              <cachedir>${config.home.path}/lib/fontconfig/cache</cachedir>

              <match target="font">
               <edit mode="assign" name="rgba">
                <const>rgb</const>
               </edit>
              </match>
              <match target="font">
               <edit mode="assign" name="hinting">
                <bool>true</bool>
               </edit>
              </match>
              <match target="font">
               <edit mode="assign" name="hintstyle">
                <const>hintslight</const>
               </edit>
              </match>
              <match target="font">
               <edit mode="assign" name="antialias">
                <bool>true</bool>
               </edit>
              </match>
            '';
          };
        };
    };
}
